import './ActionPopupPage4Repository.scss';
import Dropdown from '../../../../Widgets/Dropdown/Dropdown';
import InputField from '../../../../Widgets/InputField/InputField';

function ActionPopupPage4Repository(props) {

    const {
        repositories,
        onRepositoryDestinationDropdownChange,
        repositoryDestination,
        outputFileName,
        onFileOutputNameChange,
        minerObject,
    } = props;

    return (
        <div className='ActionPopup-wizard-step4'>
            <Dropdown
                options = {repositories}
                onValueChange = {onRepositoryDestinationDropdownChange}
                label = {`Select the destination repository`}
                value = {repositoryDestination}
            />

            <InputField
                label = {"Name of output resource"}
                fieldType = {"text"}
                placeholder = {"Please choose a name for the output generated by the algorithm"}
                value = {outputFileName}
                onChange = {onFileOutputNameChange}
            />

            <div>
                output filetype:
            </div>
            <div>
                {`${minerObject.ResourceOutput.ResourceType} ${minerObject.ResourceOutput.FileExtension ? minerObject.ResourceOutput.FileExtension : ""}`}
            </div>
        </div> 
    );
}

export default ActionPopupPage4Repository;